### PR TITLE
Changed some contents of readme.

### PR DESCRIPTION
**Pull request by 0zKillua**
Description of "why " section in readme is edited appropriately(as per my understanding). 
Open to further communication. Thank you.

### CODE REVIEW

**Review by SuwannaTruss — CHANGES_REQUESTED** [review]
Thank you Sri Harsha for your comment and the updated suggestion.
I have not saved it after amending this section and I would like to merge your readme content.
But can you keep the code challenge solution on your forked repo or create another branch on this repo? Thank you.

**Comment by 0zKillua** [comment]
Hey, i forgot to make a new branch in the start, my bad. now i reverted my commits to bring back the code solution.

**Comment by 0zKillua** [comment]
Let me know if it works for you, or i can create a new pull request all together. :)

**Review by SuwannaTruss — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
